### ISSUE TITLE
Websocket порт и хост

### ISSUE THREAD

**Issue by drfill** [andrewshkovskii/grissli_test#1]
Добрый,

В качестве хоста и порта в файле
[static/js/index.js#L167](https://github.com/andrewshkovskii/grissli_test/blob/master/grissli_test/static/js/index.js#L167)
указано 
`var ws = new WebSocket('ws://127.0.0.1:8000/events/');`
лучше заменить на 
`var ws = new WebSocket('ws://'+document.location.hostname+':'+(document.location.port || '80')+'/events/');`

для того чтоб проблемы ушли, т.к. не всегда проект запускается из под локалхоста, а в частности Docker на OSX(Kitematic/MacPorts).

**Comment by andrewshkovskii** [comment]
Добрый день.
Запускал под OS X 10.11.5, докер из .app-файла, compose ставится с ним же - проблем не было.

Сейчас поправлю.

**Comment by drfill** [comment]
Boot2Docker запускается из под VirtualBox, с "local-only" адаптером, которому при запуске выдается рандомный адрес... В моем случае было "192.168.99.100"

**Comment by andrewshkovskii** [comment]
Если мы стартуем на 0.0.0.0 хосте машины - тогда хардкод ввиде адреса сокет-сервера - проблема.
Решение есть, сейчас организую.

**Comment by drfill** [comment]
A зачем такие хардкоды, если можем нативно получить хост и порт... проблема сразу отпадет.

**Comment by andrewshkovskii** [comment]
Дело в том, там было, что:

1) Я делал малый упор и тестирование фронт-енда с различными кейсами деплоя.
2) Не имея полного представления о том, каким подводные камни могут быть при запуске из-под докера и интерфейса с адресом 0.0.0.0 сделал хардкод.

Вот зачем он появился. Т.е. не зачем - а почему.

Спасибо.
